#!/bin/bash

# Determine the directory containing this script
if [[ -n $BASH_VERSION ]]; then
    _SCRIPT_LOCATION=${BASH_SOURCE[0]}
elif [[ -n $ZSH_VERSION ]]; then
    _SCRIPT_LOCATION=${funcstack[1]}
else
    echo "Only bash and zsh are supported"
    return 1
fi

get_dirname() {
    echo "$(cd "$(dirname "$1")" && pwd)"
}

run_activate_scripts() {
    _CONDA_D="$1"
    if [[ -d "$_CONDA_D" ]]; then
        for f in $(find "$_CONDA_D" -name "*.sh"); do echo "Sourcing $f"; source $f; done
    fi
}


_THIS_DIR=$(get_dirname "$_SCRIPT_LOCATION")
CONDA_ENV_PATH=$(get_dirname "$_THIS_DIR")

export PATH="$_THIS_DIR:$PATH"
run_activate_scripts "${CONDA_ENV_PATH}/etc/conda/activate.d" &&
"$@"
