#!/bin/bash

run_activate_scripts() {
    ACTIVATE_D="$1"
    if [[ -d "$ACTIVATE_D" ]]; then
        for f in $(find "$ACTIVATE_D" -name "*.sh"); do source "$f"; done
    fi
}

export CONDA_DEFAULT_ENV="__CONDA_ENV_DIR__"
export CONDA_ENV_PATH="$CONDA_DEFAULT_ENV"

export PATH="$CONDA_DEFAULT_ENV/bin:$PATH"
run_activate_scripts "$CONDA_DEFAULT_ENV/etc/conda/activate.d" &&
"$@"
